services:
  app:
    build: .
    depends_on:
      - postgres
      - mongo
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    entrypoint: ["/app/entrypoint.sh"]
    command: ["python", "src/main.py"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  redis:
    image: redis:6
    ports:
      - "6379:6379"